### ISSUE TITLE
Bad performance

### ISSUE THREAD

**Issue by mattiio** [terminalPoltergeist/Spicetify-turnTable#7]
So I installed the extension and after installing spotify began to lag very noticeably.
When scrolling through my Playlists the animation got slowed down very much too.
And also after minimizing and maximizing the album art, the animation stopped completely.
I don´t know if its a problem on my end or not.

**Comment by terminalPoltergeist** [comment]
It has not caused lagging in other Spotify functions, but there have been issues with the animation halting or skipping. The album art minimize/maximize has not been addressed yet, but I plan to fix it at some point (see #2). Been busy with school lately. If you're interested in collaborating lmk!

**Comment by terminalPoltergeist** [comment]
I also removed the extension from Marketplace for the time being until it actually does something and doesn't break the rest of Spotify.

**Comment by mattiio** [comment]
I'd love to collaborate but i dont know anything about coding.
Yeah about the lagging, it's probably just my old PC acting up.
Good luck with your school stuff tho.

**Comment by terminalPoltergeist** [comment]
Thanks! Lmk if there's something you want to get involved with and need someone to talk through things with.
